name: ci

on:
  pull_request:
    branches:
      - master
    paths:
      - 'zammad/**'

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          exclude_file: .github/kubeval.sh
          ignore_words_list: iam,aks
          check_filenames: true
          check_hidden: true

  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_YAML: false

  lint-chart:
    runs-on: ubuntu-latest
    env: 
      CT_CONFIG_DIR: .github/ct.yaml    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - super-linter
    strategy:
      matrix:
        k8s:
          - v1.16.4
          - v1.17.4
          - v1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh 

  install-chart:
    name: install-chart
    env: 
      CT_CONFIG_DIR: .github/ct.yaml
    runs-on: ubuntu-latest
    needs: 
      - lint-chart
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.16.15
          - v1.17.11
          - v1.18.8
          - v1.19.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'
      - name: Run chart-testing (install)
        run: ct install
